//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResoucreNhanVien {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcenNhanVien {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcenNhanVien() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fifness.Resoucres.ResourcenNhanVien", typeof(ResourcenNhanVien).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ.
        /// </summary>
        public static string DIACHI {
            get {
                return ResourceManager.GetString("DIACHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới Thiệu.
        /// </summary>
        public static string GIOITHIEU {
            get {
                return ResourceManager.GetString("GIOITHIEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới Tính.
        /// </summary>
        public static string GIOITINH {
            get {
                return ResourceManager.GetString("GIOITINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình.
        /// </summary>
        public static string HINH {
            get {
                return ResourceManager.GetString("HINH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HINHmh.
        /// </summary>
        public static string HINHmh {
            get {
                return ResourceManager.GetString("HINHmh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức Vụ.
        /// </summary>
        public static string MACV {
            get {
                return ResourceManager.GetString("MACV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách Hàng.
        /// </summary>
        public static string MAKH {
            get {
                return ResourceManager.GetString("MAKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Nhân Viên.
        /// </summary>
        public static string MANV {
            get {
                return ResourceManager.GetString("MANV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Điện Thoại.
        /// </summary>
        public static string SDT {
            get {
                return ResourceManager.GetString("SDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Nhân Viên.
        /// </summary>
        public static string TENNV {
            get {
                return ResourceManager.GetString("TENNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string VietNamese {
            get {
                return ResourceManager.GetString("VietNamese", resourceCulture);
            }
        }
    }
}
