//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fifness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOP()
        {
            this.HOCSINHs = new HashSet<HOCSINH>();
            this.THUCDONTHEOTUANs = new HashSet<THUCDONTHEOTUAN>();
        }
    
        public int MA_LOP { get; set; }
        public string TEN_LOP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> ID_BUA_AN { get; set; }
        public Nullable<int> MANV { get; set; }
    
        public virtual BUAAN BUAAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOCSINH> HOCSINHs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUCDONTHEOTUAN> THUCDONTHEOTUANs { get; set; }
    }
}
