//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fifness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MONAN()
        {
            this.THUCDONTHEOTUANs = new HashSet<THUCDONTHEOTUAN>();
        }
    
        public int ID_MON_AN { get; set; }
        public string TEN_MON { get; set; }
        public Nullable<int> ID_NHOM_THUC_AN { get; set; }
    
        public virtual NHOM_THUC_AN NHOM_THUC_AN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUCDONTHEOTUAN> THUCDONTHEOTUANs { get; set; }
    }
}
