//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fifness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIEN
    {
        public int MATV { get; set; }
        public string LOAITV { get; set; }
        public Nullable<int> MAKH { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
