//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fifness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUCDONTHEOTUAN
    {
        public int ID_THUC_DON { get; set; }
        public Nullable<int> ID_BUA_AN { get; set; }
        public Nullable<int> ID_MON_AN { get; set; }
        public Nullable<int> MA_LOP { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
    
        public virtual BUAAN BUAAN { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual MONAN MONAN { get; set; }
    }
}
